### ISSUE TITLE
logstash not working for Netfloow Version 9 flows

### ISSUE THREAD

**Issue by rajutech76** [logstash-plugins/logstash-codec-netflow#64] opened 2016-12-24 05:13 UTC
Hi Team ,
During my testing it seems that logstah 5.1.1 is sending WARN message to process Netflow 9 messages
In my setup Netflow 5 version is working fine .
Any body knows root cases for this issue

My error message are given below

[2016-12-23T05:22:30,245][WARN ][logstash.codecs.netflow ] No matching template for flow id 256
[2016-12-23T05:22:30,267][WARN ][logstash.codecs.netflow ] Unsupported field {:type=>0, :length=>0}
[2016-12-23T05:22:30,268][WARN ][logstash.codecs.netflow ] Unsupported field {:type=>0, :length=>0}
[2016-12-23T05:22:30,270][WARN ][logstash.codecs.netflow ] Unsupported field {:type=>0, :length=>0}
[2016-12-23T05:22:30,270][WARN ][logstash.codecs.netflow ] No matching template for flow id 256
[2016-12-23T05:22:30,275][WARN ][logstash.codecs.netflow ] Unsupported field {:type=>0, :length=>0}
[2016-12-23T05:22:30,276][WARN ][logstash.codecs.netflow ] No matching template for flow id 256
[2016-12-23T05:22:30,305][WARN ][logstash.codecs.netflow ] Unsupported field {:type=>0, :length=>0}
[2016-12-23T05:22:30,306][WARN ][logstash.codecs.netflow ] Unsupported field {:type=>0, :length=>0}
[2016-12-23T05:22:30,310][WARN ][logstash.codecs.netflow ] No matching template for flow id 257
[2016-12-23T05:22:30,323][WARN ][logstash.codecs.netflow ] Unsupported field {:type=>0, :length=>0}
[2016-12-23T05:22:30,329][WARN ][logstash.codecs.netflow ] Unsupported field {:type=>0, :length=>0}
[2016-12-23T05:22:30,330][WARN ][logstash.codecs.netflow ] No matching template for flow id 256

For all general issues, please provide the following details for fast resolution:

- Version:logstash5.1.1
- Operating System:CentOs7
- Config File (if you have sensitive info, please remove it):
input {
udp{
port => 9995
## metadata => "true"
codec => netflow{
	versions => [5,9,10]
                 
            }
            type=> "netflow"
    }
}

output {
stdout { codec => rubydebug }
}

- Sample Data:
- Steps to Reproduce:

Pcap file is attached

 with this issues

**Comment by jorritfolmer** [comment] 2016-12-25 09:01
Hi never seen this issue before!
Can you attach your pcap so I can look at it?

**Comment by rajutech76** [comment] 2016-12-26 04:04
Hi 
Re 
[0001.zip](https://github.com/logstash-plugins/logstash-codec-netflow/files/672505/0001.zip)

sending pcap .

**Comment by jorritfolmer** [comment] 2017-01-06 16:48
I'm a bit short on time, I'll take a look at it this weekend.

**Comment by jorritfolmer** [comment] 2017-01-23 08:28
Thanks again for your pcap, and patience :)
Fixed in the most recent commit to master.
Can you confirm?

**Comment by rajutech76** [comment] 2017-01-23 15:35
Thanks Jorrit ,
I will integrate lastet code base on my test env and will conform you.

**Comment by rajutech76** [comment] 2017-03-13 07:58
Hi Jorrit,
sorry for the delay ,.Due to other high priority activities I am not able to verify the fix .
whether fix is avilable in logstash 5.2.1 . In 5.2.1 I am facing same issue again .

[2017-03-13T13:18:41,700][WARN ][logstash.codecs.netflow  ] Unsupported field {:type=>0, :length=>0}
[2017-03-13T13:18:41,712][WARN ][logstash.codecs.netflow  ] Unsupported field {:type=>0, :length=>0}
[2017-03-13T13:18:41,714][WARN ][logstash.codecs.netflow  ] No matching template for flow id 256


I am  from java background .I dont have any idea how to apply rubby patches to the build .
If you have fix Kindly advise me how can I apply fix to the logstash 5.2.1 .

**Comment by jorritfolmer** [comment] 2017-03-15 14:43
I've just released v3.4.0, so you can use the regular channels to update the plugin:

```
bin/logstash-plugin update logstash-codec-netflow
```

**Comment by jorritfolmer** [comment] 2017-07-19 18:39
Any update on this?

**Comment by nameraj** [comment] 2017-07-25 21:11
I have same issue. it is not working. I have upgraded logstash-codec-netflow to 3.5.1

**Comment by jorritfolmer** [comment] 2017-07-26 07:09
There must be another issue then. After the fix, I'm not able to reproduce the error by replaying the .pcap provided by @rajutech76.

@nameraj can you provide a pcap with 2 minutes of Netflow traffic?
Also, what device are you exporting from?

**Closed** 2017-09-04 07:26 UTC
