### ISSUE TITLE
logstash-codec-netflow 3.5.2 crashes when used with Logstash 6.0.0-beta2

### ISSUE THREAD

**Issue by robcowart** [logstash-plugins/logstash-codec-netflow#90] opened 2017-09-17 09:40 UTC
- Version: Logstash 6.0.0-beta2, logstash-codec-netflow 3.5.2

- Operating System: Centos 7 (3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux)

- Config File (if you have sensitive info, please remove it): Two pipelines running (using new multiple pipeline feature), one listening on 2055, the other on 9996. Config were the same...
```
input {
  udp {
    id => "input-netflow"
    type => "netflow"
    port => "${ELASTIFLOW_NETFLOW_PORT:2055}"
    codec => netflow {
      versions => [5,9]
    }
  }
}

output {
  redis {
    id => "output-redis"
    data_type => "list"
    key => "logstash:elastiflow:netflow:v%{[netflow][version]}"
  }
}
```

- Sample Data: Issues occurs when receiving flows from a VyOS router or FrowTraq flowexporter

- Steps to Reproduce: Start a pipeline using the 
Start pipelines and wait, errors will occur and eventually the plugin will no longer function.

```
[2017-09-11T05:38:01,471][ERROR][logstash.inputs.udp      ] Exception in inputworker {"exception"=>#<NoMethodError: undefined method `value' for nil:NilClass>, "backtrace"=>["/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-codec-netflow-3.5.2/lib/logstash/codecs/netflow/util.rb:50:in `block in get'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.0/lib/bindata/array.rb:208:in `block in each'", "org/jruby/RubyArray.java:1734:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.0/lib/bindata/array.rb:208:in `each'", "org/jruby/RubyEnumerable.java:825:in `collect'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-codec-netflow-3.5.2/lib/logstash/codecs/netflow/util.rb:50:in `get'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.0/lib/bindata/primitive.rb:112:in `sensible_default'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.0/lib/bindata/base_primitive.rb:147:in `_value'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.0/lib/bindata/primitive.rb:104:in `do_num_bytes'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.0/lib/bindata/struct.rb:258:in `block in sum_num_bytes_below_index'", "org/jruby/RubyRange.java:485:in `each'", "org/jruby/RubyEnumerable.java:936:in `inject'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.0/lib/bindata/struct.rb:255:in `sum_num_bytes_below_index'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.0/lib/bindata/struct.rb:251:in `sum_num_bytes_for_all_fields'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.0/lib/bindata/struct.rb:149:in `do_num_bytes'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.0/lib/bindata/base.rb:168:in `num_bytes'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-codec-netflow-3.5.2/lib/logstash/codecs/netflow.rb:249:in `decode_netflow9'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-codec-netflow-3.5.2/lib/logstash/codecs/netflow.rb:117:in `block in decode'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.0/lib/bindata/array.rb:208:in `block in each'", "org/jruby/RubyArray.java:1734:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.0/lib/bindata/array.rb:208:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-codec-netflow-3.5.2/lib/logstash/codecs/netflow.rb:113:in `decode'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-udp-3.1.2/lib/logstash/inputs/udp.rb:118:in `inputworker'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-udp-3.1.2/lib/logstash/inputs/udp.rb:89:in `block in udp_listener'"]}
[2017-09-11T05:38:01,471][ERROR][logstash.inputs.udp      ] Exception in inputworker {"exception"=>#<NoMethodError: undefined method `value' for nil:NilClass>, "backtrace"=>["/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-codec-netflow-3.5.2/lib/logstash/codecs/netflow/util.rb:50:in `block in get'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.0/lib/bindata/array.rb:208:in `block in each'", "org/jruby/RubyArray.java:1734:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.0/lib/bindata/array.rb:208:in `each'", "org/jruby/RubyEnumerable.java:825:in `collect'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-codec-netflow-3.5.2/lib/logstash/codecs/netflow/util.rb:50:in `get'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.0/lib/bindata/primitive.rb:112:in `sensible_default'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.0/lib/bindata/base_primitive.rb:147:in `_value'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.0/lib/bindata/primitive.rb:104:in `do_num_bytes'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.0/lib/bindata/struct.rb:258:in `block in sum_num_bytes_below_index'", "org/jruby/RubyRange.java:485:in `each'", "org/jruby/RubyEnumerable.java:936:in `inject'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.0/lib/bindata/struct.rb:255:in `sum_num_bytes_below_index'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.0/lib/bindata/struct.rb:251:in `sum_num_bytes_for_all_fields'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.0/lib/bindata/struct.rb:149:in `do_num_bytes'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.0/lib/bindata/base.rb:168:in `num_bytes'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-codec-netflow-3.5.2/lib/logstash/codecs/netflow.rb:217:in `block in decode_netflow9'", "org/jruby/RubyKernel.java:1120:in `catch'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-codec-netflow-3.5.2/lib/logstash/codecs/netflow.rb:179:in `block in decode_netflow9'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.0/lib/bindata/array.rb:208:in `block in each'", "org/jruby/RubyArray.java:1734:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.0/lib/bindata/array.rb:208:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-codec-netflow-3.5.2/lib/logstash/codecs/netflow.rb:178:in `decode_netflow9'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-codec-netflow-3.5.2/lib/logstash/codecs/netflow.rb:117:in `block in decode'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.0/lib/bindata/array.rb:208:in `block in each'", "org/jruby/RubyArray.java:1734:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.0/lib/bindata/array.rb:208:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-codec-netflow-3.5.2/lib/logstash/codecs/netflow.rb:113:in `decode'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-udp-3.1.2/lib/logstash/inputs/udp.rb:118:in `inputworker'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-udp-3.1.2/lib/logstash/inputs/udp.rb:89:in `block in udp_listener'"]}
```

**Comment by jorritfolmer** [comment] 2017-09-18 11:49
It looks like issue originates in the mac address parsing.
We have a number of known working pcaps with mac addresses in the test suite so I assume there is something weird going on in your netflows.

Can you provide a pcap sample? You can send it to my email (in profile).
One minute tcpdump is usually enough.

**Comment by jorritfolmer** [comment] 2017-09-28 14:48
@robcowart Can you send me a pcap sample to I can look into this?

**Comment by robcowart** [comment] 2017-09-28 15:43
I can’t get a pcap until I get off the road. I have been using the plugin for over a year with the same sources and without any issues. The issue didn’t show up until I started testing with Logstash 6.0.0-beta2. You would also need a much larger pcap, sometime it crashes in a couple hours, sometime in a couple days. So you will most likely need a constant stream for a longer period of time. I suspect it is more of a Logstash issue. I am waiting until 6.0.0-rc1 (should be released later today) and I will retest.

**Comment by jorritfolmer** [comment] 2017-09-28 17:23
Ah right, pcap won't help much then indeed.

You could try to use `workers => 1` in the UDP input, to eliminate any concurrency issues.
I suspect many difficult to reproduce issues stem from the fact we're don't handle concurrent access properly for the netflow templates.

**Comment by robcowart** [comment] 2017-09-28 17:26
That's interesting. Since 6.0.0 support multiple concurrent pipelines, I not only have multiple workers, I have multiple pipelines (listening on different ports). That could compound any concurrency issues.

**Comment by jorritfolmer** [comment] 2017-09-28 20:26
I've added a quick commit (1ac96fed92e909368f0696b5351cdf5401ddc3c9) in the mutex branch that seems to help with the reproducible concurrency error #91 we're having.

I'm very curious if this quick fix helps with your crashes.

**Comment by jorritfolmer** [comment] 2017-11-11 08:37
Any update on this?

**Comment by robcowart** [comment] 2017-11-11 12:50
I am waiting for GA of 6.0 before any further testing.

**Comment by jorritfolmer** [comment] 2017-11-11 13:32
Ah yes makes sense! Thanks for the update!

**Comment by jorritfolmer** [comment] 2017-11-19 16:32
Update: [netflow_stress.py](https://github.com/logstash-plugins/logstash-codec-netflow/blob/master/spec/codecs/netflow_stress.py) reliably crashes Logstash with the same exceptions you were getting.
Within 1 minute.

We have a reliable reproducer, that I like.
What I don't like is the fact that the mutex patch I just merged into master doesn't fix it.
I'll look into it further, next weekend probably.

**Comment by robcowart** [comment] 2017-11-19 16:45
Cool... glad you have a way to predictably reproduce it. I assume you tested against 6.0.0 and 5.x works fine in the same scenario. I have been using Logstash 5.x versions for Netflow for over a year. It was only with the 6.0.0-beta that I began to see issues. I am curious to learn what you discover.

**Comment by jorritfolmer** [comment] 2017-11-20 05:51
I've fixed some of the NilClass exceptions, even though I can't explain them based on the data going in. This is on 6.0.0. From the previous Github issues I can see some people encountering them occasionally, but they were never reproducible. Until 6.0.0.

Unfortunately they're not gone yet. I'm saving this here for a later time from last nights burn-in with netflow-stress.py, which started at 22:43

```
[2017-11-19T22:49:15,827][ERROR][logstash.inputs.udp      ] Exception in inputworker {"exception"=>#<NoMethodError: undefined method `has_parameter?' for nil:NilClass>, "backtrace"=>["/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.1/lib/bindata/struct.rb:267:in `include_obj?'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.1/lib/bindata/struct.rb:109:in `block in snapshot'", "org/jruby/RubyArray.java:1734:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.1/lib/bindata/struct.rb:107:in `snapshot'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.1/lib/bindata/base.rb:234:in `=='", "uri:classloader:/jruby/kernel/basicobject.rb:4:in `!='", "/home/jfolmer/logstash-codec-netflow/lib/logstash/codecs/netflow.rb:243:in `decode_netflow9'", "/home/jfolmer/logstash-codec-netflow/lib/logstash/codecs/netflow.rb:119:in `block in decode'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.1/lib/bindata/array.rb:208:in `block in each'", "org/jruby/RubyArray.java:1734:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.1/lib/bindata/array.rb:208:in `each'", "/home/jfolmer/logstash-codec-netflow/lib/logstash/codecs/netflow.rb:115:in `decode'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-udp-3.1.2/lib/logstash/inputs/udp.rb:118:in `inputworker'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-udp-3.1.2/lib/logstash/inputs/udp.rb:89:in `block in udp_listener'"]}
[2017-11-19T23:02:18,421][ERROR][logstash.inputs.udp      ] Exception in inputworker {"exception"=>#<NoMethodError: undefined method `has_parameter?' for nil:NilClass>, "backtrace"=>["/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.1/lib/bindata/struct.rb:267:in `include_obj?'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.1/lib/bindata/struct.rb:109:in `block in snapshot'", "org/jruby/RubyArray.java:1734:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.1/lib/bindata/struct.rb:107:in `snapshot'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.1/lib/bindata/base.rb:234:in `=='", "uri:classloader:/jruby/kernel/basicobject.rb:4:in `!='", "/home/jfolmer/logstash-codec-netflow/lib/logstash/codecs/netflow.rb:243:in `decode_netflow9'", "/home/jfolmer/logstash-codec-netflow/lib/logstash/codecs/netflow.rb:119:in `block in decode'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.1/lib/bindata/array.rb:208:in `block in each'", "org/jruby/RubyArray.java:1734:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.1/lib/bindata/array.rb:208:in `each'", "/home/jfolmer/logstash-codec-netflow/lib/logstash/codecs/netflow.rb:115:in `decode'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-udp-3.1.2/lib/logstash/inputs/udp.rb:118:in `inputworker'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-udp-3.1.2/lib/logstash/inputs/udp.rb:89:in `block in udp_listener'"]}
[2017-11-19T23:08:55,627][ERROR][logstash.inputs.udp      ] Exception in inputworker {"exception"=>#<ConcurrencyError: Detected invalid array contents due to unsynchronized modifications with concurrent users>, "backtrace"=>["org/jruby/RubyArray.java:1521:in `[]='", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.1/lib/bindata/struct.rb:223:in `instantiate_obj_at'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.1/lib/bindata/struct.rb:185:in `block in define_field_accessors_for'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.1/lib/bindata/primitive.rb:82:in `method_missing'", "/home/jfolmer/logstash-codec-netflow/lib/logstash/codecs/netflow/util.rb:20:in `get'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.1/lib/bindata/primitive.rb:112:in `sensible_default'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.1/lib/bindata/base_primitive.rb:147:in `_value'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.1/lib/bindata/primitive.rb:104:in `do_num_bytes'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.1/lib/bindata/struct.rb:258:in `block in sum_num_bytes_below_index'", "org/jruby/RubyRange.java:485:in `each'", "org/jruby/RubyEnumerable.java:936:in `inject'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.1/lib/bindata/struct.rb:255:in `sum_num_bytes_below_index'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.1/lib/bindata/struct.rb:251:in `sum_num_bytes_for_all_fields'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.1/lib/bindata/struct.rb:149:in `do_num_bytes'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.1/lib/bindata/base.rb:168:in `num_bytes'", "/home/jfolmer/logstash-codec-netflow/lib/logstash/codecs/netflow.rb:221:in `block in decode_netflow9'", "org/jruby/ext/thread/Mutex.java:148:in `synchronize'", "/home/jfolmer/logstash-codec-netflow/lib/logstash/codecs/netflow.rb:218:in `block in decode_netflow9'", "org/jruby/RubyKernel.java:1114:in `catch'", "/home/jfolmer/logstash-codec-netflow/lib/logstash/codecs/netflow.rb:181:in `block in decode_netflow9'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.1/lib/bindata/array.rb:208:in `block in each'", "org/jruby/RubyArray.java:1734:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.1/lib/bindata/array.rb:208:in `each'", "/home/jfolmer/logstash-codec-netflow/lib/logstash/codecs/netflow.rb:180:in `decode_netflow9'", "/home/jfolmer/logstash-codec-netflow/lib/logstash/codecs/netflow.rb:119:in `block in decode'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.1/lib/bindata/array.rb:208:in `block in each'", "org/jruby/RubyArray.java:1734:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.1/lib/bindata/array.rb:208:in `each'", "/home/jfolmer/logstash-codec-netflow/lib/logstash/codecs/netflow.rb:115:in `decode'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-udp-3.1.2/lib/logstash/inputs/udp.rb:118:in `inputworker'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-udp-3.1.2/lib/logstash/inputs/udp.rb:89:in `block in udp_listener'"]}
[2017-11-19T23:11:58,752][ERROR][logstash.inputs.udp      ] Exception in inputworker {"exception"=>#<TypeError: wrong argument type NilClass (expected Integer)>, "backtrace"=>["org/jruby/RubyArray.java:4394:in `pack'", "/home/jfolmer/logstash-codec-netflow/lib/logstash/codecs/netflow/util.rb:21:in `get'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.1/lib/bindata/primitive.rb:112:in `sensible_default'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.1/lib/bindata/base_primitive.rb:147:in `_value'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.1/lib/bindata/primitive.rb:104:in `do_num_bytes'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.1/lib/bindata/struct.rb:258:in `block in sum_num_bytes_below_index'", "org/jruby/RubyRange.java:485:in `each'", "org/jruby/RubyEnumerable.java:936:in `inject'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.1/lib/bindata/struct.rb:255:in `sum_num_bytes_below_index'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.1/lib/bindata/struct.rb:251:in `sum_num_bytes_for_all_fields'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.1/lib/bindata/struct.rb:149:in `do_num_bytes'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.1/lib/bindata/base.rb:168:in `num_bytes'", "/home/jfolmer/logstash-codec-netflow/lib/logstash/codecs/netflow.rb:255:in `decode_netflow9'", "/home/jfolmer/logstash-codec-netflow/lib/logstash/codecs/netflow.rb:119:in `block in decode'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.1/lib/bindata/array.rb:208:in `block in each'", "org/jruby/RubyArray.java:1734:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.1/lib/bindata/array.rb:208:in `each'", "/home/jfolmer/logstash-codec-netflow/lib/logstash/codecs/netflow.rb:115:in `decode'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-udp-3.1.2/lib/logstash/inputs/udp.rb:118:in `inputworker'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-udp-3.1.2/lib/logstash/inputs/udp.rb:89:in `block in udp_listener'"]}
[2017-11-19T23:26:37,274][ERROR][logstash.inputs.udp      ] Exception in inputworker {"exception"=>#<NoMethodError: undefined method `has_parameter?' for nil:NilClass>, "backtrace"=>["/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.1/lib/bindata/struct.rb:267:in `include_obj?'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.1/lib/bindata/struct.rb:109:in `block in snapshot'", "org/jruby/RubyArray.java:1734:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.1/lib/bindata/struct.rb:107:in `snapshot'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.1/lib/bindata/base.rb:234:in `=='", "uri:classloader:/jruby/kernel/basicobject.rb:4:in `!='", "/home/jfolmer/logstash-codec-netflow/lib/logstash/codecs/netflow.rb:243:in `decode_netflow9'", "/home/jfolmer/logstash-codec-netflow/lib/logstash/codecs/netflow.rb:119:in `block in decode'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.1/lib/bindata/array.rb:208:in `block in each'", "org/jruby/RubyArray.java:1734:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.1/lib/bindata/array.rb:208:in `each'", "/home/jfolmer/logstash-codec-netflow/lib/logstash/codecs/netflow.rb:115:in `decode'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-udp-3.1.2/lib/logstash/inputs/udp.rb:118:in `inputworker'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-udp-3.1.2/lib/logstash/inputs/udp.rb:89:in `block in udp_listener'"]}
[2017-11-19T23:32:14,007][ERROR][logstash.inputs.udp      ] Exception in inputworker {"exception"=>#<NoMethodError: undefined method `has_parameter?' for nil:NilClass>, "backtrace"=>["/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.1/lib/bindata/struct.rb:267:in `include_obj?'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.1/lib/bindata/struct.rb:109:in `block in snapshot'", "org/jruby/RubyArray.java:1734:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.1/lib/bindata/struct.rb:107:in `snapshot'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.1/lib/bindata/base.rb:234:in `=='", "uri:classloader:/jruby/kernel/basicobject.rb:4:in `!='", "/home/jfolmer/logstash-codec-netflow/lib/logstash/codecs/netflow.rb:243:in `decode_netflow9'", "/home/jfolmer/logstash-codec-netflow/lib/logstash/codecs/netflow.rb:119:in `block in decode'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.1/lib/bindata/array.rb:208:in `block in each'", "org/jruby/RubyArray.java:1734:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.1/lib/bindata/array.rb:208:in `each'", "/home/jfolmer/logstash-codec-netflow/lib/logstash/codecs/netflow.rb:115:in `decode'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-udp-3.1.2/lib/logstash/inputs/udp.rb:118:in `inputworker'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-udp-3.1.2/lib/logstash/inputs/udp.rb:89:in `block in udp_listener'"]}
```

**Comment by andrewvc** [comment] 2017-11-21 03:16
One theory, It's possible that some of this could be related to the upgrade to jruby 9k. Judging by some of those errors, this looks like a possible threadsafety issue. I'll look at the code in more depth tomorrow to see if I can spot the source.

**Comment by andrewvc** [comment] 2017-11-21 03:21
Looking at the current code it looks like there's a fair amount of work to do to make it actually threadsafe on first pass. The easy fix would be to synchronize all decoding with a mutex. I think this probably accounts for a lot of the weirdness.

I'm going to guess that perhaps something about the way 6.x runs just makes this happen more often, but it should have happened previously.

**Comment by andrewvc** [comment] 2017-11-22 13:53
I think https://github.com/logstash-plugins/logstash-codec-netflow/pull/107 should the issues reported here: https://github.com/logstash-plugins/logstash-codec-netflow/issues/90#issuecomment-345598226

**Closed** 2017-11-23 20:14 UTC
