### ISSUE TITLE
Netflow v9 is parsed incorrectly for IOS XR devices with a version >= 5.x

### ISSUE THREAD

**Issue by analogbyte** [logstash-plugins/logstash-codec-netflow#71] opened 2017-02-25 11:58 UTC
After @jorritfolmer closed #57 (thanks again!) we've upgraded some of our routers to new versions, leading to the issue described here.

- Version: logstash 5.2.1, logstash-codec-netflow 3.3.0 from logstash-plugin installation
- Operating System: CentOS 7.3.1611
- Config File (if you have sensitive info, please remove it):
```
input {
    udp {
        port => 9995
        codec => netflow
    }
}
```
- Sample Data: can be transmitted privately
- Steps to Reproduce:
1. Have a Cisco ASR9K router
2. Upgrade it to IOS XR 5.x or higher (6.x is available too, showing the same issue)
3. Have logstash parse its Netflow v9 data, notice the following bogus flows (output from Kibana via Elasticsearch, fully unaltered):
```
    "netflow": {
      "dst_as": 64,
      "forwarding_status": {
        "reason": 44,
        "status": 2
      },
      "in_pkts": 9035856,
      "first_switched": "2017-01-28T08:10:40.999Z",
      "flowset_id": 260,
      "l4_src_port": 13370,
      "in_bytes": 1371675920,
      "protocol": 148,
      "tcp_flags": 242,
      "src_as_str": "AS2370197725",
      "l4_dst_port": 65403,
      "src_as": 2370197725,
      "direction": 235,
      "output_snmp": 1610612736,
      "dst_mask": 236,
      "ipv4_dst_addr": "1.64.0.3",
      "src_tos": 144,
      "src_mask": 144,
      "in_bits": 10973407360,
      "version": 9,
      "flow_seq_num": 216110694,
      "ipv4_src_addr": "23.6.16.0",
      "dst_as_str": "AS64",
      "input_snmp": 1610612736,
      "last_switched": "2017-01-28T08:10:38.999Z",
      "flow_sampler_id": 13855,
      "bgp_ipv4_next_hop": "0.0.0.58"
    },
```
There are some issues: Note a) how fields like direction or forwarding status are unusual and b) that the destination related fields (ipv4_src, bgp_next_hop, ...) are rubbish (the only real IP is the src, which is a public Akamai cache), c) the flow voume (pkts and bits) is very large, d) the snmp interface IDs are large and not present on the source router

4. A search in a very large pcap sample with Wireshark's CFLOW parser does not yield any matches for, e.g. cflow.inputint > 1000 (thats input_snmp in logstashs lingo)

We currently have an open TAC case with Cisco Support in which we try to get exact documentation on any changes to the Netflow exporter between 4.x and 5.x, I hope we can get something from them.

**Comment by jorritfolmer** [comment] 2017-02-26 16:19
Can you send the pcap? I've fixed some padding issues in the nbar branch, perhaps there are other padding issues we havent run into before.

**Comment by analogbyte** [comment] 2017-02-26 16:50
Done. Should I try the nbar branch tomorrow or are those unrelated fixes?

**Comment by jorritfolmer** [comment] 2017-02-27 06:35
Unrelated probably.

I replayed your pcap, but I don't get any bogus flows with the current master branch.
Do you use the new caching template caching feature? Perhaps this causes new flowsets to be decoded by the old templates, at most temporarily. This would require the old and new templates to be identical in size, but with rearranged fields.

Another possibility is that you're hitting one of the 2 longstanding bugs that prevent the codec from distinguishing (e.g.) template 260 sent from an ASR9k v4 from template 260 sent from an ASR9k v5+. My assumption is that the templates differ, but not in size. The codec doesn't have access to exporter's IP information, so templates with the same id get overwritten regardless of source.

**Comment by analogbyte** [comment] 2017-02-27 10:05
I do not think we're using the template caching? Is it enabled by default? Still, the effects we're seeing do not seem temorarily.

Your second guess sound reasonable, but how come it's always the v5+ data that is parsed badly, but never the v4 data? It should be the other way round occasionally when restarting the logstash service? This means, we will we try to move our v5+ routers to a separate logstash instance. Anything else we can test?

**Comment by jorritfolmer** [comment] 2017-02-27 10:32
Hmm yes you would expect the behaviour to change after restart.

Looking at your pcap again, I only see 1 source. Is that because of NAT, or because you only captured 1 source? Since I don't get bogus data from that flow, it would suggest multiple-sources-using-different-templates-with-the-same-id-bug.
To understand what's really happening, I'd have to look at a pcap with Netflow traffic from both v4 and v5+ routers.

Moving the v5+ routers to another Logstash instance would be  good test. Even better to move them one at a time and monitoring the output for bugus data.

**Comment by analogbyte** [comment] 2017-02-27 10:57
I only captured one affected source (the one with the highest rate of bogus packets). I'll send you a full dump in a minute. Okay, I will test with multiple instances later this week, maybe even tomorrow.

**Comment by jorritfolmer** [comment] 2017-02-28 16:51
Thanks for the pcaps.
It seems you're experiencing the same symptoms as issues #9 and #21:
- router A sends template id 260 with source 2177
- router B sends template id 260 with source 2177

Result: netflow codec can't distinguish between router A and B based on netflow data alone.

This will be fixed when we move to logstash-input-netflow, which does have access to socket information like source IP, so we can distinguish senders on source ip too.

**Comment by jorritfolmer** [comment] 2017-11-11 08:33
I'm closing this issue to prevent duplicate issues from filling up the issue tracker.
Issues #9 and #21 will remain open to keep track of addressing the root cause.

**Closed by jorritfolmer** 2017-11-11 08:33 UTC
Labels: work in progress

**Comment by robcowart** [comment] 2019-11-16 10:26
This issue will be addressed once the following PRs are merged and released for the...

Logstash UDP Input: https://github.com/logstash-plugins/logstash-input-udp/pull/46
Logstash Netflow Codec: https://github.com/logstash-plugins/logstash-codec-netflow/pull/187
