### ISSUE TITLE
logstash unable to parse netflow if the netflow are sent from different sources like ASA and cisco router

### ISSUE THREAD

**Issue by hkshirish** [logstash-plugins/logstash-codec-netflow#21] opened 2015-09-21 06:29 UTC
Is it possible to configure logstash  to parse netflow records from different sources like CISCO ROUTER and CISCO-ASA. 

When I send the netflows only form one of the sources(cisco router or cisco asa), the logstash is able to decode it. 

But the issue is when both sources send the the netflow records.  

I keep getting following messages when I send netflows from both ASA and cisco router.

Template length doesn't fit cleanly into flowset {:template_id=>257, :template_length=>139, :record_length=>48, :level=>:warn}
Template length doesn't fit cleanly into flowset {:template_id=>256, :template_length=>94, :record_length=>8, :level=>:warn}

Is it possible to configure logstash  to receive netflow records from different sources like CISCO ROUTER and CISCO-ASA. 

Below is the logstash configuration for netflow. 

input {
    udp {
      port => 9995
      codec => netflow {
      versions => [9]

```
  }
}
```

  }

  output {
    stdout { codec => rubydebug }
    elasticsearch {
    index => "logstash_all-%{+YYYY.MM.dd}"
    host => "localhost"
      }
    }

> :warn}
> Template length doesn't fit cleanly into flowset {:template_id=>256, :template_length=>94, :record_length=>8, :level=>:warn}

below is the logstash configuration for netflow. 

input {
    udp {
      port => 9995
      codec => netflow {
      versions => [9]

```
  }
}
```

  }

  output {
    stdout { codec => rubydebug }
    elasticsearch {
    index => "logstash_all-%{+YYYY.MM.dd}"
    host => "localhost"
      }
    }

**Comment by jorritfolmer** [comment] 2015-09-24 06:50
This is a duplicate of Issue #6.
You should try to apply the fix from Pull Request https://github.com/logstash-plugins/logstash-codec-netflow/pull/16.
This worked for me, I had similar issues.

**Comment by hkshirish** [comment] 2015-10-08 09:44
I applied the fix, But when multiple sources are configured to send V9 records (in my case it is ASA and cisco router), Some of the flows of the cisco router are missing.
This works find when I have cisco ASA send v9 records and cisco-router send v5 records)

**Comment by jorritfolmer** [comment] 2015-10-08 18:29
Could you run a tcpdump on the Logstash server when both the ASA and Cisco router send netflow data? I think 5 minutes should be enough to capture both templates and data.
`tcpdump -i eth0 -s 0 -w /tmp/cisco_asa_plus_router.pcap`
And post the resulting .pcap file somewhere public, for example on pastebin.com?

**Comment by hkshirish** [comment] 2015-10-09 13:57
I am not able to attach the pcap in pastebin, please email me "shktech9@gmail.com" where I can send the pcap.
 Below I am pasting the templates for CISCO router  and CISCO ASA which I got from this capture.
![asa](https://cloud.githubusercontent.com/assets/14539726/10395628/a93cf838-6ebb-11e5-9d72-50a72ddb9fdf.png)

![cisco_router](https://cloud.githubusercontent.com/assets/14539726/10395560/44beacd0-6ebb-11e5-823b-e3909a1f6d9d.png)

**Comment by jorritfolmer** [comment] 2015-10-09 18:24
From the screenshots it seems you are hitting issue #9.
Both the Cisco router and Cisco ASA send netflow packets with the same SourceID 0.
They also send Data Templates with the same TempateID 256, 257 etc.

However, the templates differ. Since the logstash-codec-netflow only uses SourceID and TemplateID, one of these netflow streams will not be parsed properly, because e.g. the ASA template is applied to Cisco router data, which fails.

I'm afraid until we have some method to pass an IP address to the codec to help differentiate different netflow exporters with identical SourceID and TemplateID,  you'll have to work around this issue by using v5 netflow for the router and v9 for the firewall.

**Comment by jorritfolmer** [comment] 2015-10-13 20:11
Thanks for providing the .pcap through email! 
With the .pcap file I have been replaying the asa and router netflows to my own logstash. 
That gave a lot of these for the ASA netflow:

````
Unsupported field {:type=>148, :length=>4, :level=>:warn}
Unsupported field {:type=>176, :length=>1, :level=>:warn}
````

So I've added all the fields to the netflow.yaml file (see PR #24), and after that I was able to receive both v9 router and asa netflows:

````
{
    "@timestamp" => "2015-10-09T09:52:10.000Z",
       "netflow" => {
                "version" => 9,
           "flow_seq_num" => 12260,
             "flowset_id" => 256,
          "last_switched" => "2015-10-09T09:52:20.999Z",
         "first_switched" => "2015-10-09T09:51:21.999Z",
               "in_bytes" => 4788,
                "in_pkts" => 57,
             "input_snmp" => 1,
            "output_snmp" => 2,
          "ipv4_src_addr" => "192.168.23.20",
          "ipv4_dst_addr" => "164.164.37.11",
               "protocol" => 1,
                "src_tos" => 0,
            "l4_src_port" => 0,
            "l4_dst_port" => 2048,
        "flow_sampler_id" => 0,
          "ipv4_next_hop" => "192.168.14.50",
               "dst_mask" => 24,
               "src_mask" => 24,
              "tcp_flags" => 16,
              "direction" => 1,
                 "dst_as" => 0,
                 "src_as" => 0
    },
      "@version" => "1",
          "host" => "172.16.32.201"
}
{
    "@timestamp" => "2015-10-09T09:47:51.000Z",
       "netflow" => {
                    "version" => 9,
               "flow_seq_num" => 662,
                 "flowset_id" => 265,
                    "conn_id" => 8500,
              "ipv4_src_addr" => "192.168.14.1",
                "l4_src_port" => 0,
                 "input_snmp" => 3,
              "ipv4_dst_addr" => "2.2.2.11",
                "l4_dst_port" => 17549,
                "output_snmp" => 2,
                   "protocol" => 1,
                  "icmp_type" => 0,
                  "icmp_code" => 0,
        "xlate_src_addr_ipv4" => "192.168.14.1",
        "xlate_dst_addr_ipv4" => "2.2.2.11",
             "xlate_src_port" => 0,
             "xlate_dst_port" => 17549,
                   "fw_event" => 2,
               "fw_ext_event" => 2025,
            "event_time_msec" => 1444384069599,
         "in_permanent_bytes" => 56,
            "flow_start_msec" => 1444384067569,
             "ingress_acl_id" => 4814546854973423139954884608,
              "egress_acl_id" => 0,
                   "username" => ""
    },
      "@version" => "1",
          "host" => "172.16.32.201"
}
````

Which flows of the Cisco router are you missing exactly when receiving v9 records from both router and asa?

**Comment by hkshirish** [comment] 2015-10-15 06:56
Flows were missing when ASA sends template and cisco router  send the data.  
Also to double check I started 2 instances of logstash , in one instance I had configured to receive the netflow form both asa and cisco router listening on port 9995. In another instance I had configured the netflow for only cisco router listening on 9996. 

After that  check the count of netflow records(for cisco router) received  both instances, lot of flows for cisco were missing for case1 where netflow was configured for both asa+ciscorouter.

In case2 where netflow was configured only for cisco router, I could see all the records being received.

**Comment by jorritfolmer** [comment] 2015-10-15 07:45
Ah yes I see. It appears I didn't reproduce your issue properly. I replayed the template+data from the router, and then replayed the template+data from the ASA. Which works obviously, but like you said, the issue is in receiving template from router, then template+data from ASA and then data (without template) from the router.

Since the ASA template packet contains template ids 256 to 268, it will overwrite the router template id 256 if it is sent later because they share the same source id.

Until there is a fix for issue #9, I think your workaround of using another Logstash instance is best.

**Comment by jorritfolmer** [comment] 2015-10-21 09:20
I think I've fixed the issue, perhaps you could test?

I've added another commit to PR #20. It now also takes into account the IP and port from the netflow exporters, so that templates sent from your ASA don't overwrite the ones from your router.
Based on the .pcap you provided, this seems to work now.

It does however need this patch to logstash-input-udp, to provide the necessary metadata to the netflow codec:

````diff
--- a/lib/logstash/inputs/udp.rb
+++ b/lib/logstash/inputs/udp.rb
@@ -30,6 +30,9 @@ class LogStash::Inputs::Udp < LogStash::Inputs::Base
   # before packets will start dropping.
   config :queue_size, :validate => :number, :default => 2000
 
+  # Should the event's metadata be included?
+  config :metadata, :validate => :boolean, :default => false
+
   public
   def initialize(params)
     super
@@ -92,10 +95,21 @@ class LogStash::Inputs::Udp < LogStash::Inputs::Base
       while true
         payload, client = @input_to_worker.pop
 
-        @codec.decode(payload) do |event|
-          decorate(event)
-          event["host"] ||= client[3]
-          @output_queue.push(event)
+        if @metadata
+          metadata_to_codec = {}
+          metadata_to_codec["port"] = client[1]
+          metadata_to_codec["host"] = client[3]
+          @codec.decode(payload, metadata_to_codec) do |event|
+            decorate(event)
+            event["host"] ||= client[3]
+            @output_queue.push(event)
+          end
+        else
+          @codec.decode(payload) do |event|
+            decorate(event)
+            event["host"] ||= client[3]
+            @output_queue.push(event)
+          end
         end
       end
     rescue => e
````

And an extra parameter **metadata => true** to your logstash conf like this:
````
input {
    udp {
      port => 9995
      metadata => true
      codec => netflow {
        versions => [5,9,10]
      }
    }
}
````

**Comment by jorritfolmer** [comment] 2016-12-03 13:01
Update: This will be addressed in the migration to logstash-plugins/logstash-input-netflow#1.
It will allow us to own the network socket directly and use the necessary IP addresses that we need to differentiate between netflow exporters. As a codec, instead of a plugin, we need to jump through too many hoops and touch too many other plugins.
Probably 2017 though.

**Comment by jorritfolmer** [comment] 2017-11-23 20:28
I'm closing this issue because we already track it in #9

**Closed by jorritfolmer** 2017-11-23 20:28 UTC
Labels: roadmap, work in progress

**Comment by robcowart** [comment] 2019-11-16 10:36
This issue will be addressed once the following PRs are merged and released for the...

Logstash UDP Input: https://github.com/logstash-plugins/logstash-input-udp/pull/46
Logstash Netflow Codec: https://github.com/logstash-plugins/logstash-codec-netflow/pull/187
